//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HybridCryptography
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_table
    {
        public int admin_ID { get; set; }
        public string admin_name { get; set; }
        public string admin_password { get; set; }
        public Nullable<int> document_ID { get; set; }
        public string admin_loginDate { get; set; }
        public string admin_createdDate { get; set; }
        public string admin_email { get; set; }
    
        public virtual document_table document_table { get; set; }
    }
}
