//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HybridCryptography
{
    using System;
    using System.Collections.Generic;
    
    public partial class document_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public document_table()
        {
            this.admin_table = new HashSet<admin_table>();
        }
    
        public int document_ID { get; set; }
        public byte[] document_content { get; set; }
        public string document_created_date { get; set; }
        public string document_extension { get; set; }
        public Nullable<int> user_ID { get; set; }
        public string document_keyAes { get; set; }
        public string document_keyDes { get; set; }
        public string document_keyRc2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin_table> admin_table { get; set; }
        public virtual user_table user_table { get; set; }
    }
}
