//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HybridCryptography
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hybrid_CryptographyEntities : DbContext
    {
        public Hybrid_CryptographyEntities()
            : base("name=Hybrid_CryptographyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_table> admin_table { get; set; }
        public virtual DbSet<document_table> document_table { get; set; }
        public virtual DbSet<user_table> user_table { get; set; }
    }
}
