//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HybridCryptography
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_table()
        {
            this.document_table = new HashSet<document_table>();
        }
    
        public int user_ID { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string user_loginDate { get; set; }
        public string user_createdDate { get; set; }
        public string user_email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document_table> document_table { get; set; }
    }
}
